### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by rob-gordon** [wp-sync-db/wp-sync-db-cli#10]
Hey, I'm just wondering what the status of this project is. Is this still a functioning wp-cli plugin? I ask because I don't see it in the wp-cli package repository, and there isn't much documentation here about how to install it. 
Let me know how to install it if so, otherwise I may fork and keep working on it.

Thanks!

**Comment by palomnik** [comment]
This will be a highly useful add-on, and I too am wondering when and if it will become production ready.

**Comment by ghost** [comment]
I second (third) this.

**Comment by wokawoka** [comment]
+1

**Comment by ryantcarter** [comment]
I know the comments are a little old on this thread, but I'd like to chip in as I've just spent a little time finding the commands for this.

The plugin is to be installed as a standard plugin, ensure you have wp-sync-db installed as well and have WP-CLI installed on your server.

Firstly, you'll want to set up a profile for the sync. So go ahead in your WP backend and set up the migration. Save the profile. You can have multiple profiles if you'd like.

Profiles are numerical, saved in order of how they're listed in the backend.

Commands for WP-CLI are:

`wp wpsdb migrate [profile-number]`

Example:
`wp wpsdb migrate 1`
